Trivia_Cog py
ClemBotProject/ClemBot pull request #657
Opened 2022-05-10 01:25 UTC by STEVE4git

-Trivia cog with unique parsing, asyncio operations for speed etc.

2022-05-10 03:57 UTC, Jay-Madden requested changes
Initial review, primarily focusing on the low hanging fruit and the argument parsing in the manual command, the async task review will come after

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +
we dont use headers like this in clembot

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +import uuid
this is unused

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +import bot.bot_secrets as bot_secrets
This is unused

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +        "Use !trivia to return a random assortment of 10 trivia questions. React with emojis to submit your answer choice")
we dont need to use the `!trivia` command invocation here becuase its handled by the example field

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +        "!trivia use !trivia m for custom arguments")
Same as above, this should just be a short version of the long description

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +    async def trivia(self, ctx):
We need the @ext.example() decorator as well

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +        "Say you want only bool question types (True/False) and default everything else: !trivia m 10 0 0 2 The only truly required argument is Question Number. You can use 0's for categories you don
the example field is for examples of the command being invoked, this description can go in the long help string

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +        "Say you want only bool question types (True/False) and default everything else: !trivia m 10 0 0 2 The only truly required argument is Question Number. You can use 0's for categories you don
you can add multiple examples by passing in a comma seperated list

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +        return
redundant return
```suggestion
```

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +        return
redundant return 
```suggestion
```

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +        return
redundant return
```suggestion
```

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +        return
redundant return
```suggestion
```

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +    async def html_parser(self, new_response):
This doesnt need to be async

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +                                x.find(difficulty) != -1):  #Searches the substring. If this ever comes up, its not a bug you can type in a and not find your category GIGO. It is better than exact ca
why is this on a new line

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +                "There isn't enough questions in that category. Lower your question amount or select another! Or select a different question type!")
nit: single quotes

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +#Stephen Martin
All the strings need to be switched to single quotes

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +#Stephen Martin
putting this here instead of leaving 100 individual comments

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +                        url += ("&category=" + str(function_list[1]))
this should be an f string

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +                        url += ("&difficulty=" + function_list[2])
this should be an f string

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +                        url += ("&type=" + function_list[max_index])
this should be an f string

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +                            "Category Number out of bounds(Number has to be 1-24) or enter the category you want! Type ?trivia help to see the category list")
We need to grab the actual command prefix for the context guild and interpolate it into this string

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +                            "Difficulty Number out of bounds(Number has to be 1-3) or enter Easy-Hard! Type ?trivia help to see the difficulty list.")
We need to grab the actual command prefix for the context guild and interpolate it into this string

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +                            "Question type number out of bounds(1 or 2) 1: Multiple Choice 2: Boolean. Type ?trivia help to see our question types.")
We need to grab the actual command prefix for the context guild and interpolate it into this string

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +                                y))  #This HTML response is in a weird format where you have to navigate a list that contains dictionaries with that dictionary containing a SINGLE list
why is this on a new line?

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +            embed = discord.Embed(title="Question #" + str(x) + ":",
this should be an f string

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +                embed.add_field(name="Answer Choice  " + chr(a) + " :", value=iterative, inline=False)
this should be an f string

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +    @ext.short_help("!trivia m <Question Number> <category/substring/number> <Difficulty/Number> <question type>")
the short help is just a shorter version of long help to show in the help embed home page, this stuff should be in the example section

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +            Right_Answer = create_lists['correct_answer']
missed a snake_case name

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +            answers_list = []
This doesnt need to be declared here, you assign a list to it on the next line

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +    async def manual(self, ctx, *input: str):
We shouldnt be doing ANY arg parsing inside teh command, we can utilize d.pys parsing rules and also custom converters here to bind all the options before the command method is invoked

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +    async def matching_function(self, case, *input: str):
As stated above this entire method will need to become custom d.py converters to remove arg parsing from the cog

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +        while sizeofcategory < new_insertion:
this can just be a normal for loop

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +        while x < sizeofcategory:
this can be a for loop

2022-05-10 03:57 UTC, Jay-Madden commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +        while new_insertion < last_size:
this can be a for loop

2022-06-24 18:55 UTC, Iapetus-11 requested changes
There's also some weird spacing/new line things, for example methods should have one new line after them and having >1 new line between lines in a function/method kinda looks weird.

2022-06-24 18:55 UTC, Iapetus-11 commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +    def cog_unload(self):
This `cog_unload` method should probably go under the `__init__` method

2022-06-24 18:55 UTC, Iapetus-11 commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +        async with await self.session.get(DEFAULT_URL) as resp:
This usage of aiohttp is incorrect, it should be `async with self.session.get(...` instead.

https://docs.aiohttp.org/en/stable/#client-example

2022-06-24 18:55 UTC, Iapetus-11 commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +            if new_reaction != None:
You should use `is not None` here instead of `!= None`

2022-06-24 18:55 UTC, Iapetus-11 commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +        for create_lists in dictionary["results"]:
Here instead of manually incrementing `x`, you should use Python's `enumerate` function. https://realpython.com/python-enumerate/

2022-06-24 18:55 UTC, Iapetus-11 commented on ClemBot.Bot/bot/cogs/trivia_cog.py
> +        return 1
This return seems to be unnecessary

2022-06-26 16:53 UTC, Jay-Madden approved these changes
the async stuff is super overengineered and more complicated then it needs to be but at this point its whatever lol

2022-06-26 17:01 UTC, merged