Error on > 1024 char mute/ban reason
ClemBotProject/ClemBot pull request #693
Opened 2022-07-20 22:01 UTC by jkriste

Fixes #651.

2022-07-21 22:22 UTC, Iapetus-11 requested changes

2022-07-21 22:22 UTC, Iapetus-11 commented on ClemBot.Bot/bot/cogs/moderation_cog/ban_cog.py
> +MAX_REASON_LENGTH = 1024
Maybe extract this to `bot/consts.py` because it's used in multiple files?

2022-07-24 02:25 UTC, Jay-Madden approved these changes
lgtm

2022-07-24 04:14 UTC, Jay-Madden approved these changes
lgtm

2022-07-24 04:15 UTC, merged