Server-wide and Channel-wide Command Disabling
ClemBotProject/ClemBot pull request #770
Opened 2022-08-21 23:22 UTC by jkriste

# Command Restrictions
This PR adds a new cog and a way to disable commands in specific channels or server-wide.

## Features
- Command Cog
  - **Name**: `command` (aliases: `cmd`)
    - **Arguments**: `<command name>`
    - Checks the status of a command for a guild and channel.
    - **Examples**: `!command help`, `!command slots`
  - **Sub-commands**:
    - **Name**: `enable`
      - **Arguments**: `<command name> [channel]`
      - **Required Claims**: `manage_commands`
      - Enables this command in a specific channel or server-wide.
      - **Examples**: `!command enable search #general-chat`, `!command enable slots`
    - **Name**: `disable`
      - **Arguments**: `<command name> [channel] [silently fail]`
      - **Required Claim**: `manage_commands`
      - Disables this command in a specific channel or server-wide. 
      - If silently fail is `true`, the user will not be notified that the command is disabled.
      - **Examples**: `!command disable trivia true`, `!command disable slots #clem-bot-discussion`
- Two new claims:
  - `manage_commands`: Allows for enabling and disabling of commands.
  - `bypass_disabled_commands`: Allows for a user or role to bypass **ANY** disabled commands.
- Cogs can optionally opt-out of allowing users to disable the command.
  - **Example**:
  ```py
  @ext.command()
  @ext.allow_disable(False)  # by default, this is set to True and is not necessary to allow disabling
  async def my_command(self, ctx: ext.ClemBotCtx) -> None:
      # ...
  ```
## API Routes
- **[GET]** `bot/commands/{GuildId}/{ChannelId}/{CommandName}/status`
  - Checks whether the given command is disabled in either the given guild or channel.
  - **Returns**:
  ```cs
  disabled: bool
  silently_fail: bool
  ```
- **[GET]** `bot/commands/{GuildId}/{ChannelId}/{CommandName}/details`
  - Gets the details for command restrictions for the given command name in the given guild and channel.
  - **Returns**:
  ```cs
  command_name: str
  disabled: bool
  guild_id: int
  channel_ids: list[int]
  ```
- **[PUT]** `bot/commands/disable`
  - Disables the given command. 
  - If the given command was previously disabled in more than 1 channel and is now being disabled server-wide, the record for the channel disable will be removed.
  - **Body**:
  ```cs
  command_name: str
  guild_id: int
  channel_id: int | None
  silently_fail: bool = False
  ```
  - **Returns**: `None`
- **[DELETE]** `bot/commands/enable`
  - Enables the given command.
  - If the given command was previously disabled in more than 1 channel and is not being enabled server-wide, the record for the channel disable will be removed.
  - **Body**:
  ```cs
  command_name: str
  guild_id: int
  channel_id: int | None
  ```
  - **Returns**: `None`
## Other
- Disallowed disabling for the `!help` and `!command` commands.
- Fixed a small typo in the `tag_cog.py` documentation (it was really bothering me).
- Renamed `CommandMetricsService` to `CommandService`.
## To-Do
- [ ] ~Beg @Jay-Madden to review the PR several times.~
- [ ] Create a migration to include the new claims and table.
- [ ] Finish enabling and disabling in the API.
- [ ] Finish enabling and disabling in the bot.
- [ ] Move claims checking to a service (as requested by @Jay-Madden).
- [ ] Check for `bypass_disabled_commands` claim pre-status.
- [ ] Test

2022-09-21 01:17 UTC, jkriste commented on ClemBot.Bot/bot/cogs/command_cog.py
> +        await ctx.send(embed=embed)
Perhaps make this embed deletable?

2022-09-21 05:16 UTC, Jay-Madden requested changes
Great PR, some organizational stuff up front, also add some new lines in the python code in some places you deem to be best. its very dense

2022-09-21 05:16 UTC, Jay-Madden commented on ClemBot.Bot/bot/api/commands_route.py
> +    ) -> tuple[bool, bool]:
This function should return a named object/class.

2022-09-21 12:13 UTC, Iapetus-11 requested changes
Please space out your Python code to make it more readable (you actually do in some places, just not everywhere :madge_distort:). My general rule of thumb is newline after dedentation or before returns.

2022-09-23 00:10 UTC, jkriste commented on ClemBot.Bot/bot/errors.py
>      def __init__(self, message: typing.Optional[str] = None):
I did not write the ConversionError class 😆

2022-09-23 03:45 UTC, Jay-Madden approved these changes
lgtm

2022-09-23 03:46 UTC, merged