more fuzzy
ClemBotProject/ClemBot pull request #772
Opened 2022-08-22 17:35 UTC by Iapetus-11

- Add fuzzy matching silent autocorrection for the `tag info` command
- Add fuzzy matched suggestions for all tag commands which use the `_check_tag_exists` method

![image](https://user-images.githubusercontent.com/38477514/185983946-ef5d8966-7c7c-4bf5-86f4-d5c299311062.png)
![image](https://user-images.githubusercontent.com/38477514/185983970-065f48db-9893-4697-af11-14e9852f1e15.png)

2022-08-24 02:48 UTC, jkriste requested changes
lgtm otherwise

2022-08-24 14:09 UTC, Iapetus-11 commented on ClemBot.Api/ClemBot.Api.Core/Features/Tags/Details.cs
> +            {
No suggesting changes? Surely you can write it.

2022-08-29 14:39 UTC, jkriste approved these changes

2022-09-13 18:22 UTC, Jay-Madden approved these changes
some small formatting stuff but i can fix that later lgtm

2022-09-13 18:24 UTC, merged