Multiple bug fixes
ClemBotProject/ClemBot pull request #861
Opened 2023-10-25 02:29 UTC by jkriste

This pull request resolves the following issues:
- Emoteboard leaderboard command, "Reactions Received" is inaccurate.
- Message handling service produces duplicate log entries on message edit.
- Message delete event does not take into account DMs.

Resolves #857.
Resolves #859.
Resolves #860.

2023-10-25 15:48 UTC, Emimendoza commented
LGTM! @Jay-Madden Pls merge :peeposit:

2023-10-25 17:59 UTC, Jay-Madden requested changes

2023-10-25 17:59 UTC, Jay-Madden commented on ClemBot.Bot/bot/services/message_handling_service.py
> +
this should be filtered in ClemBot.py with the other dm methods not here

2023-10-25 17:59 UTC, Jay-Madden commented on ClemBot.Bot/bot/services/message_handling_service.py
> +
same as above

2023-11-15 14:53 UTC, Jay-Madden approved these changes
lgtm

2023-11-15 14:53 UTC, merged